---
- hosts: kubernetes
  user: root

  tasks:
  - name: deply app on kubernetes
    command: kubectl apply -f /root/deployment.yaml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.apps/cvintilian-app